[package]
name = "owlnest"
version = "0.0.1"
edition = "2021"

[lib]
crate-type=["lib"]

[dependencies]
tokio ={version="1",features = ["full"]}
hyper = {version = "0.14", features = ["full"]}
tower = { version = "0.4", features = ["full"] }
libp2p = {version = "0.50", features=["full"]}
tower-service = "0.3.2"
axum = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
regex = "1.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "*"
xxhash-rust = {version="0.8.6",features=["xxh3"]}
futures = "0.3"
futures-timer = "3"