[package]
name = "owlnest"
version = "0.0.1"
edition = "2021"

[lib]
crate-type=["lib"]

[dependencies]
tokio ={version="1",features = ["full"]}
libp2p = {version = "0.50", features=["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "*"
xxhash-rust = {version="0.8.6",features=["xxh3"]}
futures = "0.3"
futures-timer = "3"
rustyline = "11"
chrono = "0.4"
owlnest-proc = {path="../owlnest-proc"}


[features]
full=["messaging","tethering","relay-client","relay-server"]
messaging = []
tethering = []
relay-server=[]
relay-client=[]