[package]
name = "owlnest"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
libp2p = { path = "../../../rust-libp2p/libp2p", features = ["full"] }
libp2p-swarm = { path = "../../../rust-libp2p/swarm" }
libp2p-tls = { path = "../../../rust-libp2p/transports/tls" }
libp2p-noise = { path = "../../../rust-libp2p/transports/noise" }
libp2p-yamux = { path = "../../../rust-libp2p/muxers/yamux" }
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
tracing-log = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "*"
xxhash-rust = { version = "*", features = ["xxh3"] }
futures = "0.3"
futures-timer = "3"
rustyline = "12"
chrono = "0.4"
owlnest-proc = { path = "../owlnest-proc" }
void = "1"
crossterm = "0.27"
owlnest-macro = {path = "../owlnest-macro"}